
image: maven:3.8.6-jdk-11

stages:
- build
- test

include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Code-Quality.gitlab-ci.yml 
  - template: Security/Secret-Detection.gitlab-ci.yml
  - template: Jobs/Dependency-Scanning.gitlab-ci.yml
  - template: Security/License-Scanning.gitlab-ci.yml



build-code:
  stage: build
  tags:
  - aktest
  before_script:
  - echo "=======change permission ======="
  - chmod +x maveninstall.sh
  script:
  - echo "==== Project Building Started ====="
  - "./maveninstall.sh"
  - echo "code build Successfull..."
  - pwd
  when: on_success
  artifacts:
    paths:
    - target/*.war
    expire_in: 15 days

sast:
  stage: test
  tags:
    - aktest
  artifacts:
   name: sast
   paths:
     - gl-sast-report.json
   reports:
     sast: gl-sast-report.json
   when: always
  script:
    - echo "testing the SAST job"

license_scanning:
  stage: test
  tags:
      - aktest
  dependencies: []
  rules:
    - if: $LICENSE_MANAGEMENT_DISABLED
      when: never
    - if: $CI_COMMIT_BRANCH &&
          $GITLAB_FEATURES =~ /\blicense_scanning\b/
  artifacts:
    paths:
      - gl-license-scanning-report.json 
    expire_in: never    

code_quality:
  stage: test
  artifacts:
    paths: [gl-code-quality-report.json] 



gemnasium-maven-dependency_scanning:
  stage: test
  tags:
    - aktest
  # artifacts:
  #  name: dependency_scanning
  #  paths:
  #    - gl-sbom-*.cdx.json
  #  reports:
  #    dependency_scanning: gl-sbom-*.cdx.json
  artifacts:
   name: dependency_scanning
   paths:
     - gl-dependency-scanning-report.json 
      # - retire-jsrepository.json
      # - sbom-manifest.json
     - gl-sbom-*.cdx.json
   expire_in: never      
   when: always







  
  
