# workflow:
#   rules:
#   - if: $CI_COMMIT_BRANCH != "main" && $CI_PIPELINE_SOURCE != "merge_request_event"
#     when: never
#   - when: always

image: maven:3.8.6-jdk-11



stages:
- build
- test

include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Code-Quality.gitlab-ci.yml 
  - template: Security/Secret-Detection.gitlab-ci.yml
  - template: Jobs/Dependency-Scanning.gitlab-ci.yml
  - template: Security/License-Scanning.gitlab-ci.yml
# - template: Security/Coverage-Fuzzing.gitlab-ci.yml


build-code:
  stage: build
  only:
  - main
  tags:
  - aktest
  before_script:
  - echo "=======change permission ======="
  - chmod +x maveninstall.sh
  script:
  - echo "==== Project Building Started ====="
  - "./maveninstall.sh"
  - echo "code build Successfull..."
  - pwd
  when: on_success
  artifacts:
    paths:
    - target/*.war
    expire_in: 15 days

sast:
  stage: test
  tags:
    - aktest
  artifacts:
   name: sast
   paths:
     - gl-sast-report.json
   reports:
     sast: gl-sast-report.json
   when: always
  script:
    - echo "testing the SAST job"



code_quality:
  stage: test
  artifacts:
    paths: [gl-code-quality-report.json] 



gemnasium-maven-dependency_scanning:
  stage: test
  tags:
    - aktest
  # artifacts:
  #  name: dependency_scanning
  #  paths:
  #    - gl-sbom-*.cdx.json
  #  reports:
  #    dependency_scanning: gl-sbom-*.cdx.json
  artifacts:
    paths:
      - gl-dependency-scanning-report.json 
      - retire-jsrepository.json
      - sbom-manifest.json
    expire_in: never  
    reports:
      cyclonedx: "*/gl-sbom-.cdx.json"     
    when: always

# variables:
#   IMAGE: registry.gitlab.com/fineshift/java_deploy:latest
#   DOCKERFILE_PATH: "$CI_PROJECT_DIR/Dockerfile"






  
  
