image: maven:3.6.3

clone:
  depth: full              # SonarCloud scanner needs the full history to assign issues properly

#The definitions property is used to define resources used elsewhere in your pipeline configuration.
definitions:
  caches:
    sonar: ~/.sonar/cache  # Caching SonarCloud artifacts will speed up your build
  steps:
     - step: &build
        name: Maven Build
        caches:
          - maven
        script:
          - mvn clean install
        artifacts:
          - target/*.war
          
     - step: &test
         name: Sonarcloud analysis
         caches:
          - maven
          - sonar
         script:
           - mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
          #- mvn verify sonar:sonar -Dsonar.projectKey=fs-bitbucket_registration_portal_AYqm6EfyTTYnAsqkkhUh
          #- mvn sonar:sonar -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_TOKEN
          #- mvn verify sonar:sonar -Dsonar.projectKey=fs-bitbucket_registration_portal_AYqm6EfyTTYnAsqkkhUh
       
     - step: &deploy
         name: Deployment on tomcat
         caches:
           - maven
         script:
           - mvn clean install
           - cp -rvf target/*.war /opt/tomcat/webapps/
           - ls -l /opt/tomcat/webapps/
          
    #- step: &Jfrog
        #name: Jfrog Artifactory
        #script:
         
 
    
pipelines:
   default:
     - step: *build
     - step: *test
     - step: *deploy
    #- step: *Jfrog
    

    
    
    