image: maven:3.6.3
#The definitions property is used to define resources used elsewhere in your pipeline configuration.
definitions:
  steps:
    - step: &build
        name: Maven Build
        caches:
          - maven
        script:
          - mvn clean install
        artifacts:
          - target/*.war
          
    - step: &test
        name: Analyze code with Sonarqube
        caches:
          - maven
        script:
          - mvn sonar:sonar -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_TOKEN
          
    - step: &deploy
        name: Deployment on tomcat
        script:
          - cp -rvf target/*.war /home/fs-shubhranshu/Tomcat/apache-tomcat-9.0.78/webapps
          - ls /home/fs-shubhranshu/Tomcat/apache-tomcat-9.0.78/webapps
          
pipelines:
  default:
    - step: *build
    - step: *test
    - step: *deploy