definitions:
  steps:
    - step: &build
        name: Maven Build
        caches:
          - maven
        script:
          - mvn clean install
        artifacts:
          - target/*.war
    - step: &sonar
        name: Analyze code with Sonarqube
        caches:
          - maven
        script:
          - mvn sonar:sonar -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_API_TOKEN
pipelines:
  default:
    - step: *build
    - step: *sonar