#  Template maven-build.
#  This template allows you to test and build your Java project with Maven.
#  The workflow allows running tests, code checkstyle and security scans on the default branch.
# Prerequisites: pom.xml and appropriate project structure should exist in the repository.
pipelines:
  default:
      - step:
          runs-on:
             - self.hosted
             - linux.shell
          name: Build and Test
          caches:
            - maven
          script:
            - pwd
            - ls
            #- mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
            - mvn -B verify --file pom.xml
          after-script:
            - echo "Pipeline running"
              # Collect checkstyle results, if any, and convert to Bitbucket Code.
            #- pipe: atlassian/checkstyle-report:0.3
          artifacts: # defining the artifacts to be passed to each future step.
            - target/*.war

      - step:
          name: Security Scan
          script:
            - pipe: sonarsource/sonarqube-scan:2.0.1
              variables:
                SONAR_HOST_URL: ${SONAR_HOST_URL}
                SONAR_TOKEN: ${SONAR_TOKEN}

      - step:
          runs-on:
             - self.hosted
             - linux.shell
          name: Deployment
          script:
            - cp -rvf target/*.war /home/fs-shubhranshu/Tomcat/apache-tomcat-9.0.78/webapps
            - ls /home/fs-shubhranshu/Tomcat/apache-tomcat-9.0.78/webapps