image: maven:3.6.3

definitions:
  steps:
    - step: &build
        name: Maven Build
        caches:
          - maven
        script:
          - mvn clean install
        artifacts:
          - target/*.war
          
    - step: &sonar
        name: Analyze code with Sonarqube
        caches:
          - maven
        script:
          - mvn clean verify sonar:sonar -Dsonar.token=sqp_1cabd65736eacfa65af9c46d1baadd3941ef4937
          
pipelines:
  default:
    - step: *build
    - step: *sonar