definitions:
  steps:
    - step: &build
        name: Maven Build
        caches:
          - maven
        script:
          - mvn clean install
        artifacts:
          - target/*.war
          
    - step: &test
        name: Analyze code with Sonarqube
        caches:
          - maven
        script:
          - mvn sonar:sonar -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_TOKEN
          
    -step: &deploy
        name: Deployment on tomcat
        script: