image: maven:3.6.3

clone:
  depth: full              # SonarCloud scanner needs the full history to assign issues properly

#The definitions property is used to define resources used elsewhere in your pipeline configuration.
definitions:
  caches:
    sonar: ~/.sonar/cache  # Caching SonarCloud artifacts will speed up your build
  steps:
    - step: &build
        name: Maven Build
        caches:
          - maven
        script:
          - mvn clean install
        artifacts:
          - target/*.war
          
    - step: &test
        name: Analyze code with Sonarcloud
        caches:
          - maven
          - sonar
        script:
          #- mvn sonar:sonar -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_TOKEN
          #- mvn verify sonar:sonar -Dsonar.projectKey=fs-bitbucket_registration_portal_AYqm6EfyTTYnAsqkkhUh
          - mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
       
    #- step: &deploy
       # name: Deployment on tomcat
       # caches:
       #   - maven
       # script:
         # - cp -rvf target/*.war /home/fs-shubhranshu/Tomcat/apache-tomcat-9.0.78/webapps/
         # - ls -l /home/fs-shubhranshu/Tomcat/apache-tomcat-9.0.78/webapps/
          
    - step: &Jfrog
        name: Jfrog Artifactory
        script:
           - pipe: jfrog/jfrog-setup-cli:2.0.0
           - source ./jfrog-setup-cli.sh
           # Download artifacts from Artifactory
           - jf rt dl artifacts/
           # Upload artifacts to Artifactory
           - jf rt u file artifacts/
           # Collect environment variables
           - jf rt bce
           # Publish build info
           - jf rt bp
    
pipelines:
  default:
    - step: *build
    - step: *test
    #- step: *deploy
    - step: *Jfrog